name: Feature Freeze Branch
on:
  schedule:
    - cron: '0 0 23 * *'
jobs:
  create_ff_branch:
    name: Create Feature Freeze Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: date
        run: echo "::set-output name=date::$(date -d 'next month' +'%Y.%m.01')"

      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.date.outputs.date }}
