# Documentation: https://github.com/marketplace/actions/close-stale-issues

name: "Stale issue handler"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 365
        days-before-pr-stale: 90 
        days-before-close: 30
        exempt-pr-labels: blocked
        stale-issue-message: 'This issue has been automatically marked as stale and will be closed in 30 days because it has not had recent activity and is much likely outdated. If you think this issue is still relevant and applicable, you just have to post a comment and it will be unmarked.'
        stale-pr-message: 'This pull request has been automatically marked as stale and will be closed in 30 days because it has not had recent activity and is much likely abandoned or outdated. If you think this pull request is still relevant and applicable, you just have to post a comment and it will be unmarked.'
        stale-issue-label: "stale"
        stale-pr-label: "stale"
        ascending: true
        # Never mark feature requests/enhancements as stale
        exempt-issue-labels: "feature-request,enhancement,exempt-stale"
